- name: Application Deployment
  hosts: proxy_servers
  tasks:
    - name: Create a Deployment
      kubernetes.core.k8s:
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: app-01
            namespace: dev1
          spec:
            replicas: 3
            selector:
              matchLabels:
                app: app-01
            template:
              metadata:
                labels:
                  app: app-01
              spec:
                containers:
                  - name: app-01-container
                    image: nginx:latest
                    ports:
                      - containerPort: 80

    - name: Expose Deployment as a Service
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: app-01-service
            namespace: dev1
          spec:
            selector:
              app: app-01
            ports:
              - protocol: TCP
                port: 80
                targetPort: 80
            type: LoadBalancer