---
- name: Deploy application to Kubernetes
  hosts: master
  vars:
    destination: /home/ubuntu/app
    source: /var/lib/jenkins/workspace/app-01/dev/app

  tasks:

    - name: Ensure directories exist and are empty
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - "{{ destination }}"

    - name: Copy files from source to destination
      copy:
        src: /home/ubuntu
        dest: "{{ destination }}/"
        mode: '0644'


    - name: Create app1 namespace
      shell: kubectl apply -f "{{ destination }}/namespace.yml"
      args:
        chdir: "{{ destination }}"
      register: namespace_output_app

    - name: Apply app-01 Kubernetes manifest
      shell: kubectl apply -f "{{ destination }}/app-01.yml"
      args:
        chdir: "{{ destination }}"
      register: app01_output

    - name: Apply app-01-service Kubernetes manifest
      shell: kubectl apply -f "{{ destination }}/app-01-service.yml"
      args:
        chdir: "{{ destination }}"
      register: app01_service_output

    - name: Show app1 namespace apply output
      debug:
        msg: "{{ namespace_output_app.stdout }}"

    - name: Show app-01 apply output
      debug:
        msg: "{{ app01_output.stdout }}"


    - name: Apply MySQL secret manifest
      shell: kubectl apply -f "{{ destination }}/mysql-secret.yaml"
      args:
        chdir: "{{ destination }}"
      register: mysql_secret_output

    - name: Apply MySQL database manifest
      shell: kubectl apply -f "{{ destination }}/mysql-database.yml"
      args:
        chdir: "{{ destination }}"
      register: mysql_database_output

    - name: Apply phpMyAdmin service manifest
      shell: kubectl apply -f "{{ destination }}/phpmyadmin.yaml"
      args:
        chdir: "{{ destination }}"
      register: phpmyadmin_service_output

    - name: Apply phpMyAdmin ingress manifest
      shell: kubectl apply -f "{{ destination }}/ingress.yaml"
      args:
        chdir: "{{ destination }}"
      register: ingress_output


    - name: Show MySQL database apply output
      debug:
        msg: "{{ mysql_database_output.stdout }}"

    - name: Show phpMyAdmin service apply output
      debug:
        msg: "{{ phpmyadmin_service_output.stdout }}"

    - name: Show ingress service apply output
      debug:
        msg: "{{ ingress_output.stdout }}"
