---
- name: Deploy application to Kubernetes
  hosts: master
  tasks:
    - name: Copy app manifest to master node
      copy:
        src: ./app-01.yml
        dest: /home/ubuntu/app-01.yml
        mode: '0644'

    - name: Copy app service to master node
      copy:
        src: ./app-01.yml
        dest: /home/ubuntu/app-01-service.yml
        mode: '0644'

    - name: Copy namespace manifest to master node
      copy:
        src: ./namespace.yml
        dest: /home/ubuntu/namespace.yml
        mode: '0644'

    - name: Create namespace
      shell: kubectl apply -f /home/ubuntu/namespace.yml
      args:
        chdir: /home/ubuntu
      register: namespace_output

    - name: Apply Kubernetes manifest using kubectl
      shell: kubectl apply -f /home/ubuntu/app-01.yml
      args:
        chdir: /home/ubuntu
      register: app_output

    - name: Apply Kubernetes app-01-service.yml using kubectl
      shell: kubectl apply -f /home/ubuntu/app-01-service.yml
      args:
        chdir: /home/ubuntu
      register: app_output


    - name: Show namespace apply output
      debug:
        msg: "{{ namespace_output.stdout }}"

    - name: Show app apply output
      debug:
        msg: "{{ app_output.stdout }}"
