---
- name: Deploy application to Kubernetes
  hosts: master
  become: yes
  tasks:
    
    - name: Copy manifest to master node
      copy:
        src: ./app-01.yml
        dest: /home/ubuntu/app-01.yml
        mode: '0644'

    - name: Apply Kubernetes manifest using kubectl
      shell: kubectl apply -f /home/ubuntu/app-01.yml
      args:
        chdir: /home/ubuntu
      register: apply_output

    - name: Show kubectl apply output
      debug:
        msg: "{{ apply_output.stdout }}"
