---
- name: Déploiement de l'application sur Kubernetes
  hosts: all
  become: yes 
  tasks:
    - name: Construire et pousser l'image Docker
      shell: |
        docker build -t fekam/guerinapp dev/
        docker push fekam/guerinapp

    - name: Créer un déploiement Kubernetes
      shell: kubectl apply -f dev/deployment.yml

    - name: Exposer l'application avec un service NodePort
      shell: kubectl apply -f dev/service.yml
