apiVersion: apps/v1
kind: Deployment
metadata:
  name: guerindb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guerindb
  template:
    metadata:
      labels:
        app: guerindb
    spec:
      containers:
      - name: guerindb
        image: fekam/guerindb:0.0.1
        ports:
        - name: http
          containerPort: 3306
