apiVersion: v1
kind: Service
metadata:
  name: guerindb-nodeport
spec:
  type: NodePort
  selector:
    app: guerindb-deployment
  ports:
  - name: database
    port: 3306
    hostPort: 8090
    protocol: TCP
    targetPort: 3306
