apiVersion: v1
kind: Service
metadata:
  name: guerindb-nodeport
spec:
  type: NodePort
  selector:
    app: guerindb  # This should match the label in your Deployment
  ports:
  - name: database
    port: 3306
    targetPort: 3306
    protocol: TCP
    nodePort: 30990  # Optional: specify a port in the NodePort range (30000-32767)
