---
- name: Setup and Shutdown Maven Project
  hosts: master  
  become: true  
  vars:
    maven_project_dir: "/home/ubuntu/dev2"  
  tasks:

    - name: Navigate to kubernetes directory and run run.sh
      shell: |
        cd kubernetes && ./deploy.sh
      args:
        chdir: "{{ maven_project_dir }}"  
      register: kubernetes_run_output
      

    - name: Check if kubernetes run.sh executed successfully
      debug:
        msg: "Kubernetes run.sh output: {{ kubernetes_run_output.stdout }}"
      when: kubernetes_run_output.rc == 0


    - name: Show test results
      debug:
        msg: "Maven test output: {{ test_output.stdout }}"
      when: test_output.rc == 0
      ignore_errors: yes


