---
- name: Setup and Test Maven Project
  hosts: master  
  become: true
  vars:
    maven_project_dir: "/home/ubuntu/dev2"  

  tasks:
    - name: Copy dev2 directory to the remote machine
      copy:
        src: ../dev2  
        dest: /home/ubuntu
        mode: '0755'

    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes
      when: ansible_facts['packages']['docker.io'] is not defined
  

    - name: Navigate to docker directory and run run.sh
      shell: |
        cd "{{ maven_project_dir }}"/docker && ./run.sh && ls -l
      args:
        chdir: "{{ maven_project_dir }}"
      register: docker_run_output
      ignore_errors: yes

    - name: Check if docker run.sh executed successfully
      debug:
        msg: "Docker run.sh output: {{ docker_run_output.stdout }}"
      when: docker_run_output.rc == 0

    - name: Run tests using Maven
      shell: mvn test
      args:
        chdir: "{{ maven_project_dir }}"  
      when: docker_run_output.rc == 0  
      register: test_output
      ignore_errors: yes

    - name: Show test results
      debug:
        msg: "Maven test output: {{ test_output.stdout }}"
      when: test_output.rc == 0

    - name: Fail the play if tests failed
      fail:
        msg: "Maven tests failed"
      when: test_output.rc != 0
      ignore_errors: yes
