- name: Kubernetes Dependencies
  hosts: all
  become: yes
  tasks:

- hosts: master
  become: yes
  tasks:
    - name: Install Kubectl
      apt:
        name: kubectl=1.29.*
        state: present
        force: yes