- name: Configure Join Commands on Master Node
  hosts: master
  become: yes
  tasks:
    - name: Retrieve Join Command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set Join Command as a fact on master
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: Join Worker Nodes to the Cluster
  hosts: workers
  become: yes
  tasks:
    - name: Wait for TCP port 6443 to be available on the master
      wait_for:
        host: "{{ hostvars[groups['master'][0]].ansible_host }}"
        port: 6443
        timeout: 60

    - name: Join worker nodes to the Kubernetes cluster
      shell: "{{ hostvars[groups['master'][0]].join_command }} >> node_joined.log"
      args:
        chdir: /home/ubuntu
        creates: node_joined.log
